### ISSUE TITLE
Projections to DB

### ISSUE THREAD

**Issue by mninawa** [AntonioFalcaoJr/EventualShop#675]
Hi Guys, 
thanx for the work done in the code, i would like to know if its possible to have Projections point to NoSQL and SQL server,
will it be a compromise if we have have SQL server.. please advise on this regard
M

**Comment by AntonioFalcaoJr** [comment]
Hi Paige!

For any projection, the way is basically the same, which means adding a new projection model and a new use case interactor with all events it is interested in.

If desire a different database, the better way to do that is to create a port (interface) at the application, implement it in a new infrastructure layer (like Infrastructure.SQL) and then inject it into the respective interactor.
