### ISSUE TITLE
Bug in the Queries.cs

### ISSUE THREAD

**Issue by mninawa** [AntonioFalcaoJr/EventualShop#676]
I have also picked up a bug in the Queries.cs
<img width="1255" alt="Screenshot 2023-07-17 at 11 50 39" src="https://github.com/AntonioFalcaoJr/EventualShop/assets/4068536/47d3136b-989d-4888-a82d-7aef8737b6c6">

please advise if i allowed to do a pull request and make those change...

M

**Comment by AntonioFalcaoJr** [comment]
Sure! The project is open for contributions.

But I don't think it's worth it; we are now doing a significant refactoring to support DDD principles better, and this will affect pretty much everything:

![image](https://github.com/AntonioFalcaoJr/EventualShop/assets/20262424/a0252743-f05c-4e3b-a09d-83bb15b64701)

**Comment by mninawa** [comment]
Thanx @AntonioFalcaoJr, it would be nice to contribute regardless 

M
